### ISSUE TITLE
anyone know how to make it work for wechat?

### ISSUE THREAD

**Issue by insomnia417** [jellyfin/jellyfin-plugin-webhook#152]

**Comment by serenity666** [comment]
微信企业版我测试可以，按微信企业版里的群机器人的模板填写即可。有需要可以私信我，稍微有些复杂。

**Comment by serenity666** [comment]
![IMG_20221225_105143](https://user-images.githubusercontent.com/64485323/209455630-c1170493-3b25-4e7b-a39b-8e31b3f44840.jpg)

**Comment by goadsth** [comment]
> 微信企业版我测试可以，按微信企业版里的群机器人的模板填写即可。有需要可以留言加微信，稍微有些复杂。

求个模板，我按钉钉的配置了，替换成企微的不生效

**Comment by serenity666** [comment]
> > 微信企业版我测试可以，按微信企业版里的群机器人的模板填写即可。有需要可以留言加微信，稍微有些复杂。
> 
> 求个模板，我按钉钉的配置了，替换成企微的不生效

{
    "msgtype": "news",
    "news": {
       "articles" : [
{
{{#if_equals NotificationType 'ItemAdded'}}
      {{#if_equals ItemType 'Movie'}}
          "title" :"新电影：{{{Name}}}，已入库",
          "description" : "电影时长:{{{RunTime}}}，点击查看详情",
           "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}",
           "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary"
     {{/if_equals}}
{{/if_equals}}


{{#if_equals NotificationType 'PlaybackStart'}}
   {{#if_equals ItemType 'Movie'}}
               "title" : "{{{DeviceName}}}开始播放电影：{{{Name}}}({{{Year}}})",
               "description" : "电影时长:{{RunTime}}，电影简介：{{{Overview}}}",
               "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}",
               "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Backdrop"
               {{else}}
               "title" : "{{{DeviceName}}}开始播放电视剧：{{{SeriesName}}} 第{{EpisodeNumber}}集：（{{{Name}}}）",
               "description" : "本集时长:{{{RunTime}}}，当前时间：{{{Timestamp}}}",
               "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}",
               "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary"
   {{/if_equals}}
{{/if_equals}}


{{#if_equals NotificationType 'PlaybackStop'}}
   {{#if_equals ItemType 'Movie'}}
                "title" : "{{{DeviceName}}}停止播放电影：{{{Name}}}",
               "description" : "当前时间：{{{Timestamp}}}",
               "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}",
               "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Backdrop"
               {{else}}
               "title" : "{{{DeviceName}}}停止播放电视剧：{{{SeriesName}}}",
               "description" : "当前时间：{{{Timestamp}}}",
               "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}",
               "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Backdrop"
   {{/if_equals}} 
{{/if_equals}}
           
}
}
}

**Comment by xuehuihui** [comment]
> > > 微信企业版我测试可以，按微信企业版里的群机器人的模板填写即可。有需要可以留言加微信，稍微有些复杂。
> > 
> > 
> > 求个模板，我按钉钉的配置了，替换成企微的不生效
> 
> { "msgtype": "news", "news": { "articles" : [ { {{#if_equals NotificationType 'ItemAdded'}} {{#if_equals ItemType 'Movie'}} "title" :"新电影：{{{Name}}}，已入库", "description" : "电影时长:{{{RunTime}}}，点击查看详情", "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}", "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary" {{/if_equals}} {{/if_equals}}
> 
> {{#if_equals NotificationType 'PlaybackStart'}} {{#if_equals ItemType 'Movie'}} "title" : "{{{DeviceName}}}开始播放电影：{{{Name}}}({{{Year}}})", "description" : "电影时长:{{RunTime}}，电影简介：{{{Overview}}}", "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}", "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Backdrop" {{else}} "title" : "{{{DeviceName}}}开始播放电视剧：{{{SeriesName}}} 第{{EpisodeNumber}}集：（{{{Name}}}）", "description" : "本集时长:{{{RunTime}}}，当前时间：{{{Timestamp}}}", "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}", "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary" {{/if_equals}} {{/if_equals}}
> 
> {{#if_equals NotificationType 'PlaybackStop'}} {{#if_equals ItemType 'Movie'}} "title" : "{{{DeviceName}}}停止播放电影：{{{Name}}}", "description" : "当前时间：{{{Timestamp}}}", "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}", "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Backdrop" {{else}} "title" : "{{{DeviceName}}}停止播放电视剧：{{{SeriesName}}}", "description" : "当前时间：{{{Timestamp}}}", "url" : "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}", "picurl" : "{{ServerUrl}}/Items/{{ItemId}}/Images/Backdrop" {{/if_equals}} {{/if_equals}}
> 
> } } }
我一直会报这个错误，需要去掉news 字段才可以。知道什么原因吗
Unable to send notification
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.Dictionary`2[System.String,System.String]. Path: $.news | LineNumber: 2 | BytePositionInLine: 9.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Jellyfin.Plugin.Webhook.Destinations.GenericForm.GenericFormClient.SendAsync(GenericFormOption option, Dictionary`2 data)
   at Jellyfin.Plugin.Webhook.WebhookSender.SendNotification[T](IWebhookClient`1 webhookClient, T option, Dictionary`2 itemData, Type itemType)

**Comment by xuehuihui** [comment]
> 微信企业版我测试可以，按微信企业版里的群机器人的模板填写即可。有需要可以留言加微信，稍微有些复杂。

我一直会报这个错误，用你的模版也不行，需要去掉news 字段才可以。知道什么原因吗
Unable to send notification
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.Dictionary2[System.String,System.String]. Path: $.news | LineNumber: 2 | BytePositionInLine: 9.  ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.    at System.Text.Json.Utf8JsonReader.GetString()    at System.Text.Json.Serialization.JsonDictionaryConverter3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
at System.Text.Json.Serialization.JsonConverter1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)    at System.Text.Json.Serialization.JsonConverter1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
--- End of inner exception stack trace ---
at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
at System.Text.Json.Serialization.JsonConverter1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable1 actualByteCount)    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan1 json, JsonTypeInfo jsonTypeInfo)
at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
at Jellyfin.Plugin.Webhook.Destinations.GenericForm.GenericFormClient.SendAsync(GenericFormOption option, Dictionary2 data)    at Jellyfin.Plugin.Webhook.WebhookSender.SendNotification[T](IWebhookClient1 webhookClient, T option, Dictionary`2 itemData, Type itemType)

**Comment by xuehuihui** [comment]
很奇怪，我卸载重装后就可以
