### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-plugin-webhook#226]
```
[WRN] Error sending email
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.ThrowObjectDisposedException()
   at System.Net.Sockets.Socket.GetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName)
   at System.Net.Sockets.Socket.get_ReceiveTimeout()
   at MailKit.Net.NetworkStream.get_ReadTimeout()
   at MailKit.Net.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Webhook.Destinations.Smtp.SmtpClient.SendAsync(SmtpOption option, Dictionary`2 data
```

Is this an error on my part or Jellyfin? I can not find reference on this issue.

**Comment by crobibero** [comment]
What version of Jellyfin are you using?
What version of the plugin are you using?

It's likely an issue in the plugin, but without any basic info it is impossible to say.

**Comment by crobibero** [comment]
Unfortunatly I was unable to reproduce the issue using Jellyfin v10.9 (unstable masteR) and plugin v12.2404.8.0 so I'm not sure how to help from here

It's possible that the SMTP server isn't configured correctly
