### ISSUE TITLE
Template references a helper that cannot be resolved. BlockHelper '#if_equals'

### ISSUE THREAD

**Issue by MeguMario** [jellyfin/jellyfin-plugin-webhook#228]
I tried setting up a Discord webhook the other day and met with this error below, any use of ``#if_equals`` and ``#if_exist`` cause this same error. Without those the webhook works just fine

```[2024-05-03 04:42:56.027 +00:00] [ERR] Unable to send notification
HandlebarsDotNet.HandlebarsRuntimeException: Template references a helper that cannot be resolved. BlockHelper '#if_equals'
   at HandlebarsDotNet.Helpers.BlockHelpers.MissingBlockHelperDescriptor.Invoke(EncodedTextWriter& output, BlockHelperOptions& options, Context& context, Arguments& arguments)
   at HandlebarsDotNet.Helpers.BlockHelpers.LateBindBlockHelperDescriptor.Invoke(EncodedTextWriter& output, BlockHelperOptions& options, Context& context, Arguments& arguments)
   at lambda_method2305(Closure, EncodedTextWriter&, BindingContext)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass19_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass20_0.<Compile>b__0(Object context, Object data)
   at Jellyfin.Plugin.Webhook.Destinations.BaseOption.GetMessageBody(Dictionary`2 data)
   at Jellyfin.Plugin.Webhook.Destinations.Discord.DiscordClient.SendAsync(DiscordOption option, Dictionary`2 data)
   at Jellyfin.Plugin.Webhook.WebhookSender.SendNotification[T](IWebhookClient`1 webhookClient, T option, Dictionary`2 itemData, Type itemType)
```

Template: [This template in the repo](https://github.com/jellyfin/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Templates/Discord/PlaybackStart.handlebars)
```
{
    "content": "{{MentionType}}",
    "avatar_url": "{{ServerUrl}}/Users/{{UserId}}/Images/Primary",
    "username": "{{BotUsername}}",
    "embeds": [
        {
            "author": {
                {{#if_equals ItemType 'Episode'}}
                    "name": "Playback Started • {{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} ~ {{{Name}}}",
                {{else}}
                    "name": "Playback Started • {{{Name}}} ({{Year}})",
                {{/if_equals}}

                "url": "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}"
            },
            
            "thumbnail":{
                "url": "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary"
            },

            "description": "> {{{Overview}}}\n\n``[{{PlaybackPosition}}/{{RunTime}}]``",

            "color": "3394611",

            "footer": {
                "text": "{{{ServerName}}}",
                "icon_url": "{{AvatarUrl}}"
            },
            "fields": [
            {
              "name": "User",
              "value": "{{{NotificationUsername}}}",
              "inline": true
            }
            ],

            "timestamp": "{{Timestamp}}"
        }
    ]
}
```
   
Jellyfin Version: 10.9 (2024050117)
OS: Ubuntu 22.04 LTS
Webhook Plugin: 12.2404.8.0

**Comment by John5798** [comment]
Same here on docker image 10.9

**Comment by pm3003** [comment]
Same on 10.9 Ubuntu (non-docker). Plugin compilation problem? The.cs seems in line with Handlebar guidelines.

**Comment by elendil7** [comment]
Same here, jellyfin v10.9 running in docker (image: lscr.io/linuxserver/jellyfin:latest)

**Comment by hardwareadictos** [comment]
Same here, Jellyfin 10.9.1

**Comment by GiT-BeDa** [comment]
Same here, jellyfin v10.9 running in docker (image: lscr.io/linuxserver/jellyfin:latest)

**Comment by Codingale** [comment]
Can reproduce on Jellyfin 10.9.1 and 10.9.0
I could not find Webhook version 12.2404.8.0, only 12.0.0.0 so that's interesting.
