### ISSUE TITLE
Conflicts with Email Notification plugin

### ISSUE THREAD

**Issue by exterrestris** [jellyfin/jellyfin-plugin-webhook#24]
If the Email notification plugin is installed, the Webhook plugin will be reported with a status of Malfunctioned.

Logs:
```
[2021-04-10 07:45:00.874 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2021-04-10 07:45:00.952 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "BouncyCastle.Crypto, Version=1.8.8.0, Culture=neutral, PublicKeyToken=0e99375e54769942" from "/config/data/plugins/Email_9.0.0.0/BouncyCastle.Crypto.dll"
[2021-04-10 07:45:00.959 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "MediaBrowser.Plugins.SmtpNotifications, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Email_9.0.0.0/MediaBrowser.Plugins.SmtpNotifications.dll"
[2021-04-10 07:45:00.987 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "MailKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b" from "/config/data/plugins/Email_9.0.0.0/MailKit.dll"
[2021-04-10 07:45:00.995 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "MimeKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814" from "/config/data/plugins/Email_9.0.0.0/MimeKit.dll"
[2021-04-10 07:45:01.032 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "BouncyCastle.Crypto, Version=1.8.8.0, Culture=neutral, PublicKeyToken=0e99375e54769942" from "/config/data/plugins/Webhook_2.2021.409.38/BouncyCastle.Crypto.dll"
[2021-04-10 07:45:01.049 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Handlebars, Version=2.0.4.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661" from "/config/data/plugins/Webhook_2.2021.409.38/Handlebars.dll"
[2021-04-10 07:45:01.056 +01:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/data/plugins/Webhook_2.2021.409.38/MailKit.dll". Disabling plugin.
System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[2021-04-10 07:45:01.091 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Webhook, Version=2.2021.409.38, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Webhook_2.2021.409.38/Jellyfin.Plugin.Webhook.dll"
[2021-04-10 07:45:01.099 +01:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/data/plugins/Webhook_2.2021.409.38/MimeKit.dll". Disabling plugin.
System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[2021-04-10 07:45:10.851 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Email Notifications" "9.0.0.0"
[2021-04-10 07:45:10.955 +01:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Webhook.Notifiers.GenericNotifier"
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Webhook.IWebhookSender' while attempting to activate 'Jellyfin.Plugin.Webhook.Notifiers.GenericNotifier'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by crobibero** [comment]
Ah I was afraid this would happen...
This is a bug on server, I’m not sure how to make the plugins coexist at the moment. You might be able to just remove the .dll files from the webhook folder that already exist in the email plugin folder, and update the webhook manifest.json to be `Active` instead of`Malfunctioned`

**Comment by BaronGreenback** [comment]
Could try catching and ignoring this message - may get away with it if there were only minor changes in the assembly.

I know from my plugin dev work, that two plugins can share the same version of a dll.

**Comment by nodje** [comment]
I'm having the issue as well.
but I don't see any webhook folder in the email plugin folder

**Comment by crobibero** [comment]
> I'm having the issue as well.
> but I don't see any webhook folder in the email plugin folder

It wouldn’t be in the email plugin folder. It would be next to the email plugin folder.

**Comment by nodje** [comment]
Sorry, I don't get it :(
this is what I have in the `plugins` folder:
```
Email_9.0.0.0
'Open Subtitles_12.0.0.0'
Webhook_8.0.0.0
configurations
```

**Comment by nodje** [comment]
I got it now, just deleted redundant DLLs in the Webhook plugin folder.
Not manifest.json though, only a meta.json containing a status: active though.

Anyway it works now, and I realize the SMTP Plugin is not necessary when you have Webhook working...
ANd that 10x better 'cause SMTP plugin ask you to enter SMTP server conf for each user you want to send notification to doh:

It should be stated somewhere that one need Webhook plugin to be able to send notification, period. And SMTP should be deprecated IMHO

**Comment by nodje** [comment]
Well, actually, I could edit config but the Webhook plugin wasn't working really. 
Logs were issued it complained about missing libraries like Mailkit etc. The DLLs I had removed indeed.
Trying with SMTP plugin now.

**Comment by crobibero** [comment]
> And SMTP should be deprecated IMHO

It already has been moved to the jellyfin-archive collection.
https://github.com/jellyfin-archive/jellyfin-plugin-email

I'm going to close this as the SMTP plugin is no longer maintained.
