### ISSUE TITLE
Not working with Jellyfin v10.8.0

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin-plugin-webhook#73]
I think this is probably related to my other [recently opened issue #72](https://github.com/jellyfin/jellyfin-plugin-webhook/issues/72) (and can close both upon resolution), but I just installed Jellyfin 10.8.0 via Linuxserver.io's latest image (from an hour ago) and saw an error in the logs I haven't seen before:

```
today at 9:35:01 AM [09:35:01] [ERR] [88] Jellyfin.Plugin.Webhook.WebhookSender: Unable to send notification
today at 9:35:01 AM System.TypeLoadException: Could not load type 'MediaBrowser.Common.Json.JsonDefaults' from assembly 'MediaBrowser.Common, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
today at 9:35:01 AM    at Jellyfin.Plugin.Webhook.Destinations.BaseOption.GetMessageBody(Dictionary`2 data)
today at 9:35:01 AM    at Jellyfin.Plugin.Webhook.Destinations.Discord.DiscordClient.SendAsync(DiscordOption options, Dictionary`2 data)
today at 9:35:01 AM    at Jellyfin.Plugin.Webhook.WebhookSender.SendNotification[T](IWebhookClient`1 webhookClient, T option, Dictionary`2 itemData, Type itemType)
```

**Comment by nothing2obvi** [comment]
Oops, sorry about that.
