### ISSUE TITLE
Webhook generic issue

### ISSUE THREAD

**Issue by risharde** [jellyfin/jellyfin-plugin-webhook#81]
Good day, so firstly, I tried looking for documentation to get my generic endpoint to work and it seems that there's a lack of documentation regarding how this webhook system works. For example, only after coding some endpoints, I realized data is sent by POST. This might be obvious to the creators but not obvious to everyone else.

Anyways, I tried setting up my endpoint to receive POST and basically checked all the activities in the list to be notified. I can see that my endpoint is being called yet there's no payload received (even when I check the option to ignore the template and send all properties).

The only thing I see in the logs is this (which I don't particularly understand may be unrelated but I'm not sure), I'm hoping someone can point me in the right direction. Thanks!

```
[2021-11-10 03:16:54.194 +00:00] [WRN] Error sending notification
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient.SendAsync(GenericOption options, Dictionary`2 data) 
```

**Comment by risharde** [comment]
I can also confirm my endpoint is receiving Content-type: application/json successfully but clarification as to the content-type that should be received is also appreciated for further debugging.

**Comment by crobibero** [comment]
The easiest way to make sure the plugin is working is to use something like https://webhook.site, and that it sends all of the properties- [Notifiarr](https://notifiarr.wiki/en/Website/Integrations/Jellyfin) uses this.

If you feel documentation is lacking, please feel free to edit the wiki!

**Comment by risharde** [comment]
@crobibero thank you!!! This is super helpful and definitely will consider added to documentation! Really appreciate this and also the quick response!

**Comment by risharde** [comment]
So some important notes I've learnt which might be useful to others
The Content-type: text/plain is pushed to your receiving endpoint.
This is particularly important when you're receiving notifications created by NodeJS express (in my case). NodeJS express body-parser will not recognize text/plain using default tutorials. You need to use some middleware which you can google for on how to receive text-plain content.

Thank you for the help and support! Hope this will help others out there! Closing for the meanwhile!

**Comment by crobibero** [comment]
> The Content-type: text/plain is pushed to your receiving endpoint.

You should specify the content type as a header to avoid this
