### ISSUE TITLE
Plugin malfunctioned (docker)

### ISSUE THREAD

**Issue by gnewt58** [jellyfin/jellyfin-plugin-webhook#96]
Plugin malfunctioned, it seems because assemblies are already loaded? Not sure if this is a webhook issue or jellyfin plugin management.

"Assembly with the same name is already loaded" -> "Disabling plugin"

I haven't (yet) tried removing the other plugins.

Additional info:

- Version: 10.7.7
- Operating System: Linux
- Architecture: X64

```
[08:32:34] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[08:32:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MediaBrowser.Plugins.SmtpNotifications, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Email_9.0.0.0/MediaBrowser.Plugins.SmtpNotifications.dll
[08:32:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MimeKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814 from /config/plugins/Email_9.0.0.0/MimeKit.dll
[08:32:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MailKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b from /config/plugins/Email_9.0.0.0/MailKit.dll
[08:32:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly BouncyCastle.Crypto, Version=1.8.8.0, Culture=neutral, PublicKeyToken=0e99375e54769942 from /config/plugins/Email_9.0.0.0/BouncyCastle.Crypto.dll
[08:32:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TheTVDB_6.0.0.0/TvDbSharper.dll
[08:32:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Tvdb, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TheTVDB_6.0.0.0/Jellyfin.Plugin.Tvdb.dll
[08:32:34] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/Webhook_8.0.0.0/MimeKit.dll. Disabling plugin.
System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[08:32:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Handlebars, Version=2.0.9.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661 from /config/plugins/Webhook_8.0.0.0/Handlebars.dll
[08:32:34] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/Webhook_8.0.0.0/MailKit.dll. Disabling plugin.
System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[08:32:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Webhook, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Webhook_8.0.0.0/Jellyfin.Plugin.Webhook.dll
[08:32:34] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/Webhook_8.0.0.0/BouncyCastle.Crypto.dll. Disabling plugin.
System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[08:32:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Email Notifications 9.0.0.0
[08:32:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TheTVDB 6.0.0.0
[08:32:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.7.0
[08:32:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.7.0
[08:32:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.7.0
[08:32:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Webhook.Notifiers.GenericNotifier
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Webhook.IWebhookSender' while attempting to activate 'Jellyfin.Plugin.Webhook.Notifiers.GenericNotifier'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[08:32:40] [INF] [1] Main: Kestrel listening on Any IP4 Address

```

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-plugin-webhook/issues/24
